Sync with gst git.

diff --git a/trunk/Main/GStreamer/Source/gst-plugins-bad/tools/element-maker b/trunk/Main/GStreamer/Source/gst-plugins-bad/tools/element-maker
--- a/trunk/Main/GStreamer/Source/gst-plugins-bad/tools/element-maker
+++ b/trunk/Main/GStreamer/Source/gst-plugins-bad/tools/element-maker
@@ -1,14 +1,73 @@
 #!/bin/sh
 
-class=basetransform
 
-GST_IS_REPLACE=MY_IS_EXAMPLE
-GST_REPLACE=MY_EXAMPLE
-GST_TYPE_REPLACE=MY_TYPE_EXAMPLE
-GstReplace=MyExample
-gst_replace=my_example
-gstreplace=myexample
-replace=example
+prefix=gst
+
+while [ "$1" ] ; do
+  case $1 in
+    --help)
+      cat <<-EOF
+Usage: element-maker [OPTIONS] ELEMENT_NAME BASE_CLASS
+Create a GStreamer element that subclasses BASE_CLASS.
+Options:
+  --help             Print this information
+  --prefix PREFIX    Use PREFIX instead of "gst"
+Example: 'element-maker my_element basetransform' will create the files
+  gstmyelement.c and gstmyelement.h that implement GstMyElement, a
+  subclass of GstBaseTransform, as an element named myelement.
+EOF
+      exit 0
+      ;;
+    --prefix)
+      shift
+      prefix=$1
+      ;;
+    -*)
+      echo Unknown option: $1
+      exit 1
+      ;;
+    *)
+      if [ "$name" = "" ]; then
+        name=$1
+      elif [ "$class" = "" ]; then
+        class=$1
+      else
+        echo Ignored: $1
+      fi
+  esac
+  shift
+done
+
+if [ "$name" = "" -o "$class" = "" ] ; then
+  echo "Usage: element-maker [OPTIONS] ELEMENT_NAME BASE_CLASS"
+  exit 1
+fi
+
+if [ ! -f "gst$class.c" ] ; then
+  echo "Template file for $class not found."
+  exit 1
+fi
+
+
+PREFIX=$(echo $prefix | sed -e 's/\(.*\)/\U\1/')
+NAME=$(echo $name | sed -e 's/\(.*\)/\U\1/')
+Prefix=$(echo $prefix | sed -e 's/_\(.\)/\U\1/' -e 's/^\(.\)/\U\1/')
+Name=$(echo $name | sed -e 's/_\(.\)/\U\1/' -e 's/^\(.\)/\U\1/')
+
+GST_IS_REPLACE=${PREFIX}_IS_${NAME}
+GST_REPLACE=${PREFIX}_${NAME}
+GST_TYPE_REPLACE=${PREFIX}_TYPE_${NAME}
+GstReplace=${Prefix}${Name}
+gst_replace=${prefix}_${name}
+gstreplace=${prefix}$(echo $name | sed -e 's/_//')
+replace=$(echo $name | sed -e 's/_//')
+
+if [ "$REAL_NAME" = "" ] ; then
+  REAL_NAME=FIXME
+fi
+if [ "$EMAIL_ADDRESS" = "" ] ; then
+  EMAIL_ADDRESS=fixme@example.com
+fi
 
 source=gst$class.c
 pkg=`grep -A 10000 '^% pkg-config' $source | tail -n +2|grep -m 1 -B 10000 '^%'|head -n -1`
@@ -18,7 +77,44 @@ GstBaseReplace=`grep -A 10000 '^% ClassName' $source | tail -n +2|grep -m 1 -B 1
 generate ()
 {
 
-grep -A 10000 '^% copyright' base.c | tail -n +2|grep -m 1 -B 10000 '^%'|head -n -1
+cat <<-EOF
+/* GStreamer
+ * Copyright (C) $(date +%Y) $REAL_NAME <$EMAIL_ADDRESS>
+ *
+ * This library is free software; you can redistribute it and/or
+ * modify it under the terms of the GNU Library General Public
+ * License as published by the Free Software Foundation; either
+ * version 2 of the License, or (at your option) any later version.
+ *
+ * This library is distributed in the hope that it will be useful,
+ * but WITHOUT ANY WARRANTY; without even the implied warranty of
+ * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
+ * Library General Public License for more details.
+ *
+ * You should have received a copy of the GNU Library General Public
+ * License along with this library; if not, write to the
+ * Free Software Foundation, Inc., 59 Temple Place - Suite 330,
+ * Boston, MA 02111-1307, USA.
+ */
+EOF
+
+cat <<-EOF
+/**
+ * SECTION:element-$gstreplace
+ *
+ * The $gstreplace element does FIXME stuff.
+ *
+ * <refsect2>
+ * <title>Example launch line</title>
+ * |[
+ * gst-launch -v fakesrc ! $gstreplace ! FIXME ! fakesink
+ * ]|
+ * FIXME Describe what the pipeline does.
+ * </refsect2>
+ */
+EOF
+
+#grep -A 10000 '^% copyright' base.c | tail -n +2|grep -m 1 -B 10000 '^%'|head -n -1
 
 cat <<EOF
 
@@ -82,7 +178,7 @@ gst_replace_base_init (gpointer g_class)
       gst_static_pad_template_get (&gst_replace_sink_template));
 
   gst_element_class_set_details_simple (element_class, "FIXME",
-      "Generic", "FIXME", "FIXME <fixme@example.com>");
+      "Generic", "FIXME", "$REAL_NAME <$EMAIL_ADDRESS>");
 }
 
 static void
